/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ashish
 */
public class AddEmployeeFrame extends javax.swing.JFrame {

    // ATTRIBUTES
    private MyHashTable mainHT;
    
    /**
     * Creates new form AddEmployeeFrame
     */
    public AddEmployeeFrame() {
        initComponents();
        male.setSelected(true);
        parttime.setSelected(true);
        partFrame.setVisible(true);
        fullFrame.setVisible(false);
        errorText.setVisible(false);
        errorText2.setVisible(false);
        successMessage.setVisible(false);
    }

    // METHODS
    
    public void setMainHT(MyHashTable refvalForHT) {
        mainHT = refvalForHT;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        ptefte = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeNum = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        firstNam = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        lastNam = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        deductRate = new javax.swing.JTextPane();
        male = new javax.swing.JRadioButton();
        fem = new javax.swing.JRadioButton();
        nonbin = new javax.swing.JRadioButton();
        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        parttime = new javax.swing.JRadioButton();
        fullFrame = new javax.swing.JInternalFrame();
        yearlySalary = new javax.swing.JScrollPane();
        yearSalary = new javax.swing.JTextPane();
        fLabel1 = new javax.swing.JLabel();
        partFrame = new javax.swing.JInternalFrame();
        pLabel2 = new javax.swing.JLabel();
        pLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        hourlyWages = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        hoursPerWeek = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        weeksPerYear = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        fulltime = new javax.swing.JRadioButton();
        workloc = new javax.swing.JTextField();
        errorText = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        errorText2 = new javax.swing.JLabel();
        successMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel1.setText("Add an Employee");

        jLabel2.setText("Employee Number: ");

        jLabel3.setText("First Name:");

        jLabel4.setText("Last Name:");

        jLabel5.setText("Gender:");

        jLabel6.setText("Work Location:");

        jLabel7.setText("Deduction Rate");

        employeeNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                employeeNumKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(employeeNum);

        firstNam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstNamKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(firstNam);

        lastNam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastNamKeyTyped(evt);
            }
        });
        jScrollPane6.setViewportView(lastNam);

        deductRate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                deductRateKeyTyped(evt);
            }
        });
        jScrollPane8.setViewportView(deductRate);

        genderGroup.add(male);
        male.setText("Male");

        genderGroup.add(fem);
        fem.setText("Female");

        genderGroup.add(nonbin);
        nonbin.setText("Non-Binary");

        submitButton.setText("Add Employee");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Parttime or Fulltime");

        ptefte.add(parttime);
        parttime.setText("Part-time");
        parttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parttimeActionPerformed(evt);
            }
        });

        fullFrame.setVisible(true);

        yearSalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yearSalaryKeyTyped(evt);
            }
        });
        yearlySalary.setViewportView(yearSalary);

        fLabel1.setText("Yearly Salary:");

        javax.swing.GroupLayout fullFrameLayout = new javax.swing.GroupLayout(fullFrame.getContentPane());
        fullFrame.getContentPane().setLayout(fullFrameLayout);
        fullFrameLayout.setHorizontalGroup(
            fullFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fullFrameLayout.createSequentialGroup()
                .addComponent(fLabel1)
                .addGap(0, 94, Short.MAX_VALUE))
            .addGroup(fullFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(yearlySalary, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fullFrameLayout.setVerticalGroup(
            fullFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fullFrameLayout.createSequentialGroup()
                .addComponent(fLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yearlySalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        partFrame.setVisible(true);

        pLabel2.setText("Hours per week: ");

        pLabel3.setText("Weeks per year:");

        hourlyWages.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hourlyWagesKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(hourlyWages);

        hoursPerWeek.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hoursPerWeekKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(hoursPerWeek);

        weeksPerYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                weeksPerYearKeyTyped(evt);
            }
        });
        jScrollPane5.setViewportView(weeksPerYear);

        jLabel9.setText("Hourly Wages:");

        javax.swing.GroupLayout partFrameLayout = new javax.swing.GroupLayout(partFrame.getContentPane());
        partFrame.getContentPane().setLayout(partFrameLayout);
        partFrameLayout.setHorizontalGroup(
            partFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(partFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(partFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(partFrameLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(partFrameLayout.createSequentialGroup()
                        .addComponent(pLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(partFrameLayout.createSequentialGroup()
                        .addComponent(pLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        partFrameLayout.setVerticalGroup(
            partFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(partFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(partFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(partFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pLabel2)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(partFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pLabel3)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ptefte.add(fulltime);
        fulltime.setText("Full-time");
        fulltime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fulltimeActionPerformed(evt);
            }
        });

        workloc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                worklocKeyTyped(evt);
            }
        });

        errorText.setText("Please fill out all the fields!");

        errorText2.setText("There's already an employee with that employee number in the database!");

        successMessage.setText("The Employee was added!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(partFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fullFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(errorText2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel8)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fulltime)
                                    .addComponent(parttime)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(errorText))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(submitButton)
                                .addGap(42, 42, 42)
                                .addComponent(cancelButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(male)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nonbin))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                        .addComponent(workloc))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(successMessage)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(male)
                        .addComponent(fem)
                        .addComponent(nonbin)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(workloc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(parttime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fulltime)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fullFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(partFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorText2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(successMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(cancelButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if(!employeeNum.getText().equals("") && !firstNam.getText().equals("") && !lastNam.getText().equals("") && !workloc.getText().equals("") && !deductRate.getText().equals("") && !mainHT.isInTable(Integer.parseInt(employeeNum.getText()))){
            int genderOfEmployee=0;
            if(fem.isSelected()){
                genderOfEmployee=1;
            }
            else if(nonbin.isSelected()){
                genderOfEmployee=2;
            }
            int employeeNumber=Integer.parseInt(employeeNum.getText());

            if(parttime.isSelected() && !hourlyWages.getText().equals("") && !hoursPerWeek.getText().equals("") && !weeksPerYear.getText().equals("")){
                PTE thePTE = new PTE(employeeNumber, firstNam.getText(), lastNam.getText(), genderOfEmployee, Integer.parseInt(workloc.getText()), Double.parseDouble(deductRate.getText()), Double.parseDouble(hourlyWages.getText()), Double.parseDouble(hoursPerWeek.getText()), Double.parseDouble(weeksPerYear.getText()));
                mainHT.addEmployee(thePTE);
                System.out.println("Added "+mainHT.getFromTable(employeeNumber).getFirstName()+" to the database!");
                errorText.setVisible(false);
                errorText2.setVisible(false);
                successMessage.setVisible(true);
            }
            else if(fulltime.isSelected() && !yearSalary.getText().equals("")){
                FTE theFTE = new FTE(Integer.parseInt(employeeNum.getText()), firstNam.getText(), lastNam.getText(), genderOfEmployee, Integer.parseInt(workloc.getText()), Integer.parseInt(deductRate.getText()), Double.parseDouble(yearSalary.getText()));
                mainHT.addEmployee(theFTE);
                System.out.println("Added "+mainHT.getFromTable(employeeNumber).getFirstName()+" to the database!");
                errorText.setVisible(false);
                errorText2.setVisible(false);
                successMessage.setVisible(true);
            }
            else{
                errorText.setVisible(true);
            }
        }
        else{
            if(employeeNum.getText().equals("") || firstNam.getText().equals("") || lastNam.getText().equals("") || workloc.getText().equals("") || deductRate.getText().equals("") && mainHT.isInTable(Integer.parseInt(employeeNum.getText()))){ //If fields are empty and another employee already has that employee number
                errorText.setVisible(true);
                errorText2.setVisible(true);
                successMessage.setVisible(false);
            }
            else if(mainHT.isInTable(Integer.parseInt(employeeNum.getText()))){ //If the fields are filled but the employee number is already held by another employee.
                errorText2.setVisible(true);
                successMessage.setVisible(false);
            }
            else{ //If some fields are empty
                errorText.setVisible(true);
                successMessage.setVisible(false);
            }
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void parttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parttimeActionPerformed
        // TODO add your handling code here:
        partFrame.setVisible(true);
        fullFrame.setVisible(false);
    }//GEN-LAST:event_parttimeActionPerformed

    private void fulltimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fulltimeActionPerformed
        // TODO add your handling code here:
        partFrame.setVisible(false);
        fullFrame.setVisible(true);
    }//GEN-LAST:event_fulltimeActionPerformed

    private void employeeNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeNumKeyTyped
        // TODO add your handling code here:
        char type = evt.getKeyChar();
        if(!(Character.isDigit(type))){
            evt.consume();
        }
    }//GEN-LAST:event_employeeNumKeyTyped

    private void firstNamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNamKeyTyped
        // TODO add your handling code here:
        char type = evt.getKeyChar();
        if(!(Character.isAlphabetic(type))){
            evt.consume();
        }
    }//GEN-LAST:event_firstNamKeyTyped

    private void lastNamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNamKeyTyped
        // TODO add your handling code here:
        char type = evt.getKeyChar();
        if(!(Character.isAlphabetic(type))){
            evt.consume();
        }
    }//GEN-LAST:event_lastNamKeyTyped

    private void worklocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_worklocKeyTyped
        // TODO add your handling code here:
        char type = evt.getKeyChar();
        if(!(Character.isDigit(type))){
            evt.consume();
        }
    }//GEN-LAST:event_worklocKeyTyped

    private void deductRateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deductRateKeyTyped
        // TODO add your handling code here:
        char type = evt.getKeyChar();
        if(!(Character.isDigit(type))){
            evt.consume();
        }
    }//GEN-LAST:event_deductRateKeyTyped

    private void hourlyWagesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hourlyWagesKeyTyped
        // TODO add your handling code here:
        char type = evt.getKeyChar();
        if(!(Character.isDigit(type))){
            evt.consume();
        }
    }//GEN-LAST:event_hourlyWagesKeyTyped

    private void hoursPerWeekKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hoursPerWeekKeyTyped
        // TODO add your handling code here:
        char type = evt.getKeyChar();
        if(!(Character.isDigit(type))){
            evt.consume();
        }
    }//GEN-LAST:event_hoursPerWeekKeyTyped

    private void weeksPerYearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_weeksPerYearKeyTyped
        // TODO add your handling code here:
        char type = evt.getKeyChar();
        if(!(Character.isDigit(type))){
            evt.consume();
        }
    }//GEN-LAST:event_weeksPerYearKeyTyped

    private void yearSalaryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearSalaryKeyTyped
        // TODO add your handling code here:
        char type = evt.getKeyChar();
        if(!(Character.isDigit(type))){
            evt.consume();
        }
    }//GEN-LAST:event_yearSalaryKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployeeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextPane deductRate;
    private javax.swing.JTextPane employeeNum;
    private javax.swing.JLabel errorText;
    private javax.swing.JLabel errorText2;
    private javax.swing.JLabel fLabel1;
    private javax.swing.JRadioButton fem;
    private javax.swing.JTextPane firstNam;
    private javax.swing.JInternalFrame fullFrame;
    private javax.swing.JRadioButton fulltime;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JTextPane hourlyWages;
    private javax.swing.JTextPane hoursPerWeek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextPane lastNam;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton nonbin;
    private javax.swing.JLabel pLabel2;
    private javax.swing.JLabel pLabel3;
    private javax.swing.JInternalFrame partFrame;
    private javax.swing.JRadioButton parttime;
    private javax.swing.ButtonGroup ptefte;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel successMessage;
    private javax.swing.JTextPane weeksPerYear;
    private javax.swing.JTextField workloc;
    private javax.swing.JTextPane yearSalary;
    private javax.swing.JScrollPane yearlySalary;
    // End of variables declaration//GEN-END:variables
}
