
import javax.swing.ButtonModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ashish
 */
public class EditEmployeeFrame extends javax.swing.JFrame {

    // ATTRIBUTES
    private MyHashTable mainHT;
    public int employeeFromTable;//If you click on an employee in the Show Employees table that employee's employee number will show up here
    
    /**
     * Creates new form AddEmployeeFrame
     */
    public EditEmployeeFrame() {
        initComponents();
        male.setSelected(true);
        parttime.setSelected(true);
        partFrame.setVisible(true);
        fullFrame.setVisible(false);
        errorText.setVisible(false);
        confirmationText.setVisible(false);
        notInTable.setVisible(false);
        internalEditFrame.setVisible(false);
        employeeFromTable = -1;//Will be changed if information is given.
    }

    // METHODS
    
    public void setMainHT(MyHashTable refvalForHT) {
        mainHT = refvalForHT;
    }
    
    public void setID(int id) {
        employeeFromTable = id;
        searchBar.setText(Integer.toString(id));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        ptefte = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        internalEditFrame = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        firstNam = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        parttime = new javax.swing.JRadioButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        lastNam = new javax.swing.JTextPane();
        fullFrame = new javax.swing.JInternalFrame();
        yearlySalary = new javax.swing.JScrollPane();
        yearSalary = new javax.swing.JTextPane();
        fLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        deductRate = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        fulltime = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        partFrame = new javax.swing.JInternalFrame();
        pLabel2 = new javax.swing.JLabel();
        pLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        hourlyWages = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        hoursPerWeek = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        weeksPerYear = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        workloc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fem = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        nonbin = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeNum = new javax.swing.JTextPane();
        errorText = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        confirmationText = new javax.swing.JLabel();
        searchLabel = new javax.swing.JLabel();
        searchBar = new javax.swing.JTextField();
        notInTable = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel1.setText("Edit Employee Information");

        internalEditFrame.setVisible(true);

        firstNam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstNamKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(firstNam);

        jLabel8.setText("Parttime or Fulltime");

        ptefte.add(parttime);
        parttime.setText("Part-time");
        parttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parttimeActionPerformed(evt);
            }
        });

        lastNam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastNamKeyTyped(evt);
            }
        });
        jScrollPane6.setViewportView(lastNam);

        fullFrame.setVisible(true);

        yearSalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yearSalaryKeyTyped(evt);
            }
        });
        yearlySalary.setViewportView(yearSalary);

        fLabel1.setText("Yearly Salary:");

        javax.swing.GroupLayout fullFrameLayout = new javax.swing.GroupLayout(fullFrame.getContentPane());
        fullFrame.getContentPane().setLayout(fullFrameLayout);
        fullFrameLayout.setHorizontalGroup(
            fullFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fullFrameLayout.createSequentialGroup()
                .addComponent(fLabel1)
                .addGap(0, 94, Short.MAX_VALUE))
            .addGroup(fullFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(yearlySalary, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fullFrameLayout.setVerticalGroup(
            fullFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fullFrameLayout.createSequentialGroup()
                .addComponent(fLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yearlySalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jLabel2.setText("Employee Number: ");

        jLabel3.setText("First Name:");

        deductRate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                deductRateKeyTyped(evt);
            }
        });
        jScrollPane8.setViewportView(deductRate);

        jLabel4.setText("Last Name:");

        ptefte.add(fulltime);
        fulltime.setText("Full-time");
        fulltime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fulltimeActionPerformed(evt);
            }
        });

        jLabel5.setText("Gender:");

        genderGroup.add(male);
        male.setText("Male");

        partFrame.setVisible(true);

        pLabel2.setText("Hours per week: ");

        pLabel3.setText("Weeks per year:");

        hourlyWages.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hourlyWagesKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(hourlyWages);

        hoursPerWeek.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hoursPerWeekKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(hoursPerWeek);

        weeksPerYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                weeksPerYearKeyTyped(evt);
            }
        });
        jScrollPane5.setViewportView(weeksPerYear);

        jLabel9.setText("Hourly Wages:");

        javax.swing.GroupLayout partFrameLayout = new javax.swing.GroupLayout(partFrame.getContentPane());
        partFrame.getContentPane().setLayout(partFrameLayout);
        partFrameLayout.setHorizontalGroup(
            partFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(partFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(partFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(partFrameLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(partFrameLayout.createSequentialGroup()
                        .addComponent(pLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(partFrameLayout.createSequentialGroup()
                        .addComponent(pLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        partFrameLayout.setVerticalGroup(
            partFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(partFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(partFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(partFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pLabel2)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(partFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pLabel3)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        workloc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                worklocKeyTyped(evt);
            }
        });

        jLabel6.setText("Work Location:");

        genderGroup.add(fem);
        fem.setText("Female");

        jLabel7.setText("Deduction Rate");

        genderGroup.add(nonbin);
        nonbin.setText("Non-Binary");

        employeeNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                employeeNumKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(employeeNum);

        errorText.setText("Please fill all the fields!!");

        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        confirmationText.setText("Employee Information successfully changed!");

        javax.swing.GroupLayout internalEditFrameLayout = new javax.swing.GroupLayout(internalEditFrame.getContentPane());
        internalEditFrame.getContentPane().setLayout(internalEditFrameLayout);
        internalEditFrameLayout.setHorizontalGroup(
            internalEditFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, internalEditFrameLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(errorText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(245, 245, 245))
            .addGroup(internalEditFrameLayout.createSequentialGroup()
                .addGroup(internalEditFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(internalEditFrameLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(confirmButton)
                        .addGap(80, 80, 80)
                        .addComponent(cancelButton))
                    .addGroup(internalEditFrameLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(confirmationText)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(internalEditFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(internalEditFrameLayout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addGroup(internalEditFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(internalEditFrameLayout.createSequentialGroup()
                            .addComponent(partFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fullFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(internalEditFrameLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(internalEditFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(internalEditFrameLayout.createSequentialGroup()
                                    .addGroup(internalEditFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel7))
                                    .addGroup(internalEditFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(internalEditFrameLayout.createSequentialGroup()
                                            .addGap(59, 59, 59)
                                            .addGroup(internalEditFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                                .addComponent(workloc)))
                                        .addGroup(internalEditFrameLayout.createSequentialGroup()
                                            .addGap(21, 21, 21)
                                            .addComponent(male)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(fem)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(nonbin))))
                                .addGroup(internalEditFrameLayout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(27, 27, 27)
                                    .addGroup(internalEditFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fulltime)
                                        .addComponent(parttime))))))
                    .addContainerGap(76, Short.MAX_VALUE)))
        );
        internalEditFrameLayout.setVerticalGroup(
            internalEditFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, internalEditFrameLayout.createSequentialGroup()
                .addContainerGap(482, Short.MAX_VALUE)
                .addGroup(internalEditFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, internalEditFrameLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addComponent(errorText, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmationText)
                .addGap(8, 8, 8)
                .addGroup(internalEditFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton)
                    .addComponent(cancelButton)))
            .addGroup(internalEditFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(internalEditFrameLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(internalEditFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(internalEditFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(internalEditFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(22, 22, 22)
                    .addGroup(internalEditFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(internalEditFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(male)
                            .addComponent(fem)
                            .addComponent(nonbin)))
                    .addGap(29, 29, 29)
                    .addGroup(internalEditFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(workloc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(internalEditFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(40, 40, 40)
                    .addGroup(internalEditFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(parttime))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(fulltime)
                    .addGap(18, 18, 18)
                    .addGroup(internalEditFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fullFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(partFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(83, Short.MAX_VALUE)))
        );

        searchLabel.setText("Enter Employee Number:");

        searchBar.setText("123456");
        searchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchBarKeyTyped(evt);
            }
        });

        notInTable.setText("That Employee isn't in the table!!");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(searchLabel)
                        .addGap(44, 44, 44)
                        .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(notInTable)))
                .addContainerGap(148, Short.MAX_VALUE))
            .addComponent(internalEditFrame, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchLabel)
                    .addComponent(searchButton))
                .addGap(8, 8, 8)
                .addComponent(notInTable)
                .addGap(14, 14, 14)
                .addComponent(internalEditFrame)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNamKeyTyped
        // TODO add your handling code here:
        char type = evt.getKeyChar();
        if(!(Character.isAlphabetic(type))){
            evt.consume();
        }
    }//GEN-LAST:event_firstNamKeyTyped

    private void parttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parttimeActionPerformed
        // TODO add your handling code here:
        partFrame.setVisible(true);
        fullFrame.setVisible(false);
    }//GEN-LAST:event_parttimeActionPerformed

    private void lastNamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNamKeyTyped
        // TODO add your handling code here:
        char type = evt.getKeyChar();
        if(!(Character.isAlphabetic(type))){
            evt.consume();
        }
    }//GEN-LAST:event_lastNamKeyTyped

    private void yearSalaryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearSalaryKeyTyped
        // TODO add your handling code here:
        char type = evt.getKeyChar();
        if(!(Character.isDigit(type))){
            evt.consume();
        }
    }//GEN-LAST:event_yearSalaryKeyTyped

    private void deductRateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deductRateKeyTyped
        // TODO add your handling code here:
        char type = evt.getKeyChar();
        if(!(Character.isDigit(type))){
            evt.consume();
        }
    }//GEN-LAST:event_deductRateKeyTyped

    private void fulltimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fulltimeActionPerformed
        // TODO add your handling code here:
        partFrame.setVisible(false);
        fullFrame.setVisible(true);
    }//GEN-LAST:event_fulltimeActionPerformed

    private void hourlyWagesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hourlyWagesKeyTyped
        // TODO add your handling code here:
        char type = evt.getKeyChar();
        if(!(Character.isDigit(type))){
            evt.consume();
        }
    }//GEN-LAST:event_hourlyWagesKeyTyped

    private void hoursPerWeekKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hoursPerWeekKeyTyped
        // TODO add your handling code here:
        char type = evt.getKeyChar();
        if(!(Character.isDigit(type))){
            evt.consume();
        }
    }//GEN-LAST:event_hoursPerWeekKeyTyped

    private void weeksPerYearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_weeksPerYearKeyTyped
        // TODO add your handling code here:
        char type = evt.getKeyChar();
        if(!(Character.isDigit(type))){
            evt.consume();
        }
    }//GEN-LAST:event_weeksPerYearKeyTyped

    private void worklocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_worklocKeyTyped
        // TODO add your handling code here:
        char type = evt.getKeyChar();
        if(!(Character.isDigit(type))){
            evt.consume();
        }
    }//GEN-LAST:event_worklocKeyTyped

    private void employeeNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeNumKeyTyped
        // TODO add your handling code here:
        char type = evt.getKeyChar();
        if(!(Character.isDigit(type))){
            evt.consume();
        }
    }//GEN-LAST:event_employeeNumKeyTyped

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        if(!employeeNum.getText().equals("") && !firstNam.getText().equals("") && !lastNam.getText().equals("") && !workloc.getText().equals("") && !deductRate.getText().equals("")){
            int genderOfEmployee=0;
            if(fem.isSelected()){
                genderOfEmployee=1;
            }
            else if(nonbin.isSelected()){
                genderOfEmployee=2;
            }
            int employeeNumber=Integer.parseInt(employeeNum.getText());

            if(parttime.isSelected() && !hourlyWages.getText().equals("") && !hoursPerWeek.getText().equals("") && !weeksPerYear.getText().equals("")){
                mainHT.removeEmployee(employeeNumber);
                PTE thePTE = new PTE(employeeNumber, firstNam.getText(), lastNam.getText(), genderOfEmployee, Integer.parseInt(workloc.getText()), Double.parseDouble(deductRate.getText()), Double.parseDouble(hourlyWages.getText()), Double.parseDouble(hoursPerWeek.getText()), Double.parseDouble(weeksPerYear.getText()));
                mainHT.addEmployee(thePTE);
                System.out.println("Added "+mainHT.getFromTable(employeeNumber).getFirstName()+" to the database!");
                errorText.setVisible(false);
                confirmationText.setVisible(true);
            }
            else if(fulltime.isSelected() && !yearSalary.getText().equals("")){
                mainHT.removeEmployee(employeeNumber);
                FTE theFTE = new FTE(Integer.parseInt(employeeNum.getText()), firstNam.getText(), lastNam.getText(), genderOfEmployee, Integer.parseInt(workloc.getText()), Integer.parseInt(deductRate.getText()), Double.parseDouble(yearSalary.getText()));
                mainHT.addEmployee(theFTE);
                System.out.println("Added "+mainHT.getFromTable(employeeNumber).getFirstName()+" to the database!");
                errorText.setVisible(false);
                confirmationText.setVisible(true);
            }
            else{
                errorText.setVisible(true);
            }
        }
        else{
            errorText.setVisible(true);
        }
        
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        if(mainHT.isInTable(Integer.parseInt(searchBar.getText()))){
            internalEditFrame.setVisible(true);
            notInTable.setVisible(false);
            
            //Fills in the current information for you so that you only have to change the things you need to change.
            employeeNum.setText(searchBar.getText());
            
            firstNam.setText(mainHT.getFromTable(Integer.parseInt(searchBar.getText())).getFirstName());
            lastNam.setText(mainHT.getFromTable(Integer.parseInt(searchBar.getText())).getLastName());
            int gender = mainHT.getFromTable(Integer.parseInt(searchBar.getText())).getGender();
            if(gender==0){
                male.setSelected(true);
            }
            else if(gender==1){
                fem.setSelected(true);
            }
            else{
                nonbin.setSelected(true);
            }
            workloc.setText(Integer.toString(mainHT.getFromTable(Integer.parseInt(searchBar.getText())).getWorkLoc()));
            deductRate.setText(Double.toString(mainHT.getFromTable(Integer.parseInt(searchBar.getText())).getDeductRate()));
            
            //The employee object
            EmployeeInfo employee = mainHT.getFromTable(Integer.parseInt(searchBar.getText()));
            
            //Check the status of the employee
            if(employee instanceof FTE){
                fulltime.setSelected(true);
                FTE theFTE = (FTE) employee;
                yearSalary.setText(Double.toString(theFTE.yearlySalary));
            }
            else if(employee instanceof PTE){
                PTE thePTE = (PTE) employee;
                parttime.setSelected(true);
                hourlyWages.setText(Double.toString(thePTE.hourlyWage));
                hoursPerWeek.setText(Double.toString(thePTE.hoursPerWeek));
                weeksPerYear.setText(Double.toString(thePTE.weeksPerYear));
            }
            else{
                System.out.print("ERROR: Employee type undefined");
            }
            
        }
        else{
            notInTable.setVisible(true);
        }
        
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchBarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBarKeyTyped
        // TODO add your handling code here:
        char type = evt.getKeyChar();
        if(!(Character.isDigit(type))){
            evt.consume();
        }
    }//GEN-LAST:event_searchBarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployeeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel confirmationText;
    private javax.swing.JTextPane deductRate;
    private javax.swing.JTextPane employeeNum;
    private javax.swing.JLabel errorText;
    private javax.swing.JLabel fLabel1;
    private javax.swing.JRadioButton fem;
    private javax.swing.JTextPane firstNam;
    private javax.swing.JInternalFrame fullFrame;
    private javax.swing.JRadioButton fulltime;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JTextPane hourlyWages;
    private javax.swing.JTextPane hoursPerWeek;
    private javax.swing.JInternalFrame internalEditFrame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextPane lastNam;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton nonbin;
    private javax.swing.JLabel notInTable;
    private javax.swing.JLabel pLabel2;
    private javax.swing.JLabel pLabel3;
    private javax.swing.JInternalFrame partFrame;
    private javax.swing.JRadioButton parttime;
    private javax.swing.ButtonGroup ptefte;
    private javax.swing.JTextField searchBar;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTextPane weeksPerYear;
    private javax.swing.JTextField workloc;
    private javax.swing.JTextPane yearSalary;
    private javax.swing.JScrollPane yearlySalary;
    // End of variables declaration//GEN-END:variables
}
